export enum SettingsEnum {
    SMSSENDAPP = 'SEND_SMS_APP',
    MINAFTERWORK = 'MIN_AFTER_WORK',
    SMSTEMPLATEAPP = 'SMS_TEMPLATE_APP',
    SMSTEMPLATEREMINDER = 'SMS_TEMPLATE_REMINDER',
    TIMEINTERVALCALENDAR = 'TIME_INTERVAL_CALENDAR'
}
